export interface Client {
    _id: String,
    nom: string,
    prenom: string,
    telOrange: number,
    telMtn: number,
    telCelcom: number,
    telPerso: number,
    adress: {
        commune: string,
        quartier: string,
        secteur: string
    },
    email: string,
    genre: string,
    entreprise: string,
    description: string,
    avatar: string,
    deteCmdUpdate: any,
    commandes: [{
        _id: any,
        value: any,
        typeCmd:string,
        somPay: number,
        somRest: number,
        somDoit: number,
        somCredit: number,
        typePay: string,
        modePay: string,
        numCmd: string,
        opperateur: string,
        nbStartTimes: number,
        client_id: String,
        traitement: number,
        reglement: [{
            someRegler: number,
            someRestant: number,
            modePay: string,
        }],
        update: number,
        delete: number,
        dateCmd: Date
    }],
    active: number,
    user_id: string,
}
